### ISSUE TITLE
Scope of AiService classes + memory

### ISSUE THREAD

**Issue by geoand** [mariofusco/quarkus-drools-llm#2]
Currently the scope of services annotated with `@RegisterAiService` is `@Singleton`.

When such a scope is used, the code that uses the service **must** also use take care of removing the `@MemoryId` objects from memory with `ChatMemoryRemover`. 

An alternative is to just use the default scope (`@RequestScoped`) in which case the `quarkus-langchain4j` can remove the memory objects automatically

**Comment by mariofusco** [comment]
Fixed by https://github.com/mariofusco/quarkus-drools-llm/commit/82c6ad985dde1b723c56841bd0a6be287d1cd91e
