### ISSUE TITLE
issue with dependencies

### ISSUE THREAD

**Issue by jfparrado** [mariofusco/quarkus-drools-llm#4]
When i run the command "./mvnw compile quarkus:dev". I am receiving this error:

**[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  2.385 s
[INFO] Finished at: 2024-05-31T15:39:10Z
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project quarkus-drools-llm: Could not resolve dependencies for project org.mfusco:quarkus-drools-llm:jar:1.0.0-SNAPSHOT: Could not find artifact org.drools:drools-quarkus:jar:999-SNAPSHOT -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
ubuntu@ip-172-31-18-201:~/quarkus-drools-llm$ ^C
ubuntu@ip-172-31-18-201:~/quarkus-drools-llm$ sudo docker exec -it ollama ollama run mistral./mvnw compile quarkus:dev
pulling manifest
Error: pull model manifest: file does not exist
ubuntu@ip-172-31-18-201:~/quarkus-drools-llm$
Broadcast message from root@ip-172-31-18-201 (Fri 2024-05-31 15:57:08 UTC):

The system will power off now!**

I looked in maven repository but i couldnt find that artifact.

**Comment by mariofusco** [comment]
Unfortunately I had to use a a snapshot artifact for drools (that of course is not on maven central) before it contains the changes that I need for this project. We are transitioning Drools under the Apache Foundation and have almost completed this process. I will update this project accordingly when Drools 10.0 will be finally out.

**Comment by jfparrado** [comment]
Do you think it would be possible for you to share that artifact with me before the new version is released?

**Comment by mariofusco** [comment]
> Do you think it would be possible for you to share that artifact with me before the new version is released?

I don't see a reasonable way to share all the necessary jars. The easiest thing you could do is cloning the [drools project](https://github.com/apache/incubator-kie-drools) and build it locally. A simple

`mvn clean install -Dquickly`

should do the job.
