### ISSUE TITLE
Can't find maven dependency

### ISSUE THREAD

**Issue by jmsorci** [mariofusco/quarkus-drools-llm#6]
Could not resolve dependencies for project org.mfusco:quarkus-drools-llm:jar:1.0.0-SNAPSHOT: The following artifacts could not be resolved: org.drools:drools-quarkus:jar:10.0.0 (absent): org.drools:drools-quarkus:jar:10.0.0 was not found in https://repo.maven.apache.org/maven2 during a previous attempt. This failure was cached in the local repository and resolution is not reattempted until the update interval of central has elapsed or updates are forced -> [Help 1]

When I search maven central I can't find drools-quarkus

**Comment by mariofusco** [comment]
We are migrating Drools under the Apache foundation and version 10.0.0 hasn't been publicly release yet. It should be out in 1 or 2 weeks.
